### ISSUE TITLE
inactive class on a tag don't work

### ISSUE THREAD

**Issue by jcubic** [brajeshwar/paginate#1]
There is still hover effect on a tag event if it have class inactive.

**Comment by jcubic** [comment]
The solution:
```css
.paginate a:hover:not(.inactive):not(.active),
.paginate a:focus:not(.inactive):not(.active) {
}
```
also this is handy:
```css
.paginate a.inactive, .paginate a.active {
    cursor: default;
}
```
and the same should go to dark one too.
